#!/bin/bash

# fail fast
set -o errexit
set -o nounset
set -o pipefail

indent() {
  sed -u 's/^/       /'
}

scriptname=$(basename $0)
case $# in
  4) :;;
  *) echo "$scriptname: usage: $scriptname BUILD_DIR CACHE_DIR DEST_DIR VERSION" >&2; exit 2;;
esac

build_dir="$1"
cache_dir="$2"
dest_dir="$3"
version="$4"

base_url=http://s3.amazonaws.com/cb-mirror
extension=tar.gz

prefix=/app/.heroku/vendor
package=$scriptname
dir=$package-$version
archive=$package-$version.$extension
url=$base_url/$archive
archive_dir=$cache_dir/archives
num_cpu=$(grep -c ^bogomips /proc/cpuinfo)

gtest_archive=gtest-1.7.0.tar.gz
gtest_url=$base_url/$gtest_archive

mkdir -p $archive_dir
if [ ! -f $archive_dir/$gtest_archive ]
then
  echo "Downloading $gtest_url"
  rm -f $archive_dir/$gtest_archive.new
  curl -fsLS "$gtest_url" > $archive_dir/$gtest_archive.new
  mv $archive_dir/$gtest_archive.new $archive_dir/$gtest_archive
fi
if [ ! -f $archive_dir/$archive ]
then
  echo "Downloading $url"
  rm -f $archive_dir/$archive.new
  curl -fsLS "$url" > $archive_dir/$archive.new
  mv $archive_dir/$archive.new $archive_dir/$archive
fi

echo "Extracting $gtest_archive"
mkdir -p /tmp/gtest
tar -C /tmp/gtest -xf $archive_dir/$gtest_archive
echo "Extracting $archive"
tar -C /tmp -xf $archive_dir/$archive

pushd /tmp/$dir
echo "Building $dir"
env CPPFLAGS='-I/tmp/gtest/include' ./configure --prefix=$prefix
make -j$num_cpu
make install DESTDIR=$dest_dir

popd
