#!/bin/bash

# fail fast
set -o errexit
set -o nounset
set -o pipefail

indent() {
  sed -u 's/^/       /'
}

scriptname=$(basename $0)
case $# in
  3) :;;
  *) echo "$scriptname: usage: $scriptname BUILD_DIR CACHE_DIR VERSION" >&2; exit 2;;
esac

build_dir="$1"
cache_dir="$2"
version="$3"

base_url=http://c-ares.haxx.se/download
extension=tar.gz

prefix=/app/.heroku/vendor
destdir=/tmp/destdir
package=$scriptname
dir=$package-$version
archive=$package-$version.$extension
url=$base_url/$archive

mkdir -p $cache_dir/archives
if [ ! -f $cache_dir/archives/$archive ]
then
  echo "Downloading $url"
  rm -f $cache_dir/$archive.new
  curl -L# "$url" > $cache_dir/$archive.new
  mv $cache_dir/$archive.new $cache_dir/$archive
fi

echo "Extracting $archive"
tar -C /tmp -xf $cache_dir/$archive

pushd /tmp/$dir
echo "Building $dir"
./configure --prefix=$prefix
make
make install DESTDIR=$destdir

# Delete unnecessary man pages
rm -rf $destdir/app/.heroku/vendor/share

# Copy output files into place
mkdir -p $build_dir/.heroku/vendor
rsync -aHSx $destdir/app/.heroku/vendor/. $build_dir/.heroku/vendor/.
popd
