#!/bin/bash

# fail fast
set -o errexit
set -o nounset
set -o pipefail

indent() {
  sed -u 's/^/       /'
}

scriptname=$(basename $0)
case $# in
  3) :;;
  *) echo "$scriptname: usage: $scriptname BUILD_DIR CACHE_DIR VERSION" >&2; exit 2;;
esac

build_dir="$1"
cache_dir="$2"
version="$3"

prefix=/app/.heroku/vendor
destdir=/tmp/destdir
package=ccache
dir=$package-$version
archive=$package-$version.tar.bz2
url=http://samba.org/ftp/ccache/$archive

echo "Downloading $url"
curl -L# "$url" > /tmp/$archive

echo "Extracting $archive"
tar -C /tmp -xf /tmp/$archive

pushd /tmp/$dir
echo "Building $dir"
./configure --prefix=$prefix
make
make install DESTDIR=$destdir

# Delete unnecessary man pages
rm -rf $destdir/app/.heroku/vendor/share

# Copy output files into place
mkdir -p $build_dir/.heroku/vendor
rsync -aHSx $destdir/app/.heroku/vendor/. $build_dir/.heroku/vendor/.
popd
