#!/bin/bash

# fail fast
set -o errexit
set -o nounset
set -o pipefail

indent() {
  sed -u 's/^/       /'
}

scriptname=$(basename $0)
case $# in
  4) :;;
  *) echo "$scriptname: usage: $scriptname BUILD_DIR CACHE_DIR DEST_DIR VERSION" >&2; exit 2;;
esac

build_dir="$1"
cache_dir="$2"
dest_dir="$3"
version="$4"

base_url=http://cyrusimap.org/releases
extension=tar.gz

prefix=/app/.heroku/vendor
package=$scriptname
dir=$package-$version
archive=$package-$version.$extension
url=$base_url/$archive
archive_dir=$cache_dir/archives
num_cpu=$(grep -c ^bogomips /proc/cpuinfo)
patch_dir=$(dirname $0)/../patches
patches=uuid-1.6.2-ossp.patch
patch=cyrus-sasl-2.1.26-missing-size_t.patch

mkdir -p $archive_dir
if [ ! -f $archive_dir/$archive ]
then
  echo "Downloading $url"
  rm -f $archive_dir/$archive.new
  curl -fsLS "$url" > $archive_dir/$archive.new
  mv $archive_dir/$archive.new $archive_dir/$archive
fi

echo "Extracting $archive"
tar -C /tmp -xf $archive_dir/$archive

pushd /tmp/$dir
case "$version" in
  2.1.26)
    echo "Applying patch: $patch"
    patch -p1 < $patch_dir/$patch
    ;;
esac

echo "Building $dir"
./configure --prefix=$prefix --with-plugindir=$prefix/lib/sasl2
make -j$num_cpu
make install DESTDIR=$dest_dir

# Delete unnecessary man pages
rm -rf $dest_dir/app/.heroku/vendor/share
popd
