#!/bin/bash

# fail fast
set -o errexit
set -o nounset
set -o pipefail

indent() {
  sed -u 's/^/       /'
}

scriptname=$(basename $0)
case $# in
  4) :;;
  *) echo "$scriptname: usage: $scriptname BUILD_DIR CACHE_DIR DEST_DIR VERSION" >&2; exit 2;;
esac

build_dir="$1"
cache_dir="$2"
dest_dir="$3"
version="$4"

short_version=$(echo $version | sed 's/^\([0-9]*[.][0-9]*\).*/\1/')
base_url=http://haproxy.1wt.eu/download/$short_version/src
case $version in
  *-dev*) base_url=$base_url/devel
esac
extension=tar.gz

prefix=/app/.heroku/vendor
package=$scriptname
dir=$package-$version
archive=$package-$version.$extension
url=$base_url/$archive
archive_dir=$cache_dir/archives
num_cpu=$(grep -c ^bogomips /proc/cpuinfo)

mkdir -p $archive_dir
if [ ! -f $archive_dir/$archive ]
then
  echo "Downloading $url"
  rm -f $archive_dir/$archive.new
  curl -L# "$url" > $archive_dir/$archive.new
  mv $archive_dir/$archive.new $archive_dir/$archive
fi

echo "Extracting $archive"
tar -C /tmp -xf $archive_dir/$archive

pushd /tmp/$dir
echo "Building $dir"
make -j$num_cpu PREFIX=$prefix TARGET=linux26 USE_OPENSSL=1 USE_PCRE=1 USE_PCRE_JIT=1 USE_TFO=1 PCREDIR=$build_dir/.heroku/vendor
make install-bin PREFIX=$prefix DESTDIR=$dest_dir

popd
