#!/bin/bash

# fail fast
set -o errexit
set -o nounset
set -o pipefail

indent() {
  sed -u 's/^/       /'
}

scriptname=$(basename $0)
case $# in
  4) :;;
  *) echo "$scriptname: usage: $scriptname BUILD_DIR CACHE_DIR DEST_DIR VERSION" >&2; exit 2;;
esac

build_dir="$1"
cache_dir="$2"
dest_dir="$3"
version="$4"

base_url=https://launchpad.net
extension=tar.gz

prefix=/app/.heroku/vendor
package=$scriptname
dir=$package-$version
archive=$package-$version.$extension
url=$base_url/$package/$(echo $version | sed 's/\.[0-9]*$//')/$version/+download/$archive
archive_dir=$cache_dir/archives
num_cpu=$(grep -c ^bogomips /proc/cpuinfo)
patch_dir=$(dirname $0)/../patches

mkdir -p $archive_dir
if [ ! -f $archive_dir/$archive ]
then
  echo "Downloading $url"
  rm -f $archive_dir/$archive.new
  curl -L# "$url" > $archive_dir/$archive.new
  mv $archive_dir/$archive.new $archive_dir/$archive
fi

echo "Extracting $archive"
tar -C /tmp -xf $archive_dir/$archive

pushd /tmp/$dir
echo "Building $dir"
case $version in
  # XXX: https://bugs.launchpad.net/libmemcached/+bug/1164440
  1.0.17)
    echo "Applying patch: libmemcached-1.0.17-fix-without-memcached.patch"
    patch -p0 < $patch_dir/libmemcached-1.0.17-fix-without-memcached.patch
    ;;
esac
./configure --prefix=$prefix --without-memcached
make -j$num_cpu
make install DESTDIR=$dest_dir

# Delete unnecessary man pages
rm -rf $dest_dir/app/.heroku/vendor/share
popd
