#!/bin/bash

# fail fast
set -o errexit
set -o nounset
set -o pipefail

indent() {
  sed -u 's/^/       /'
}

scriptname=$(basename $0)
case $# in
  4) :;;
  *) echo "$scriptname: usage: $scriptname BUILD_DIR CACHE_DIR DEST_DIR VERSION" >&2; exit 2;;
esac

build_dir="$1"
cache_dir="$2"
dest_dir="$3"
version="$4"

base_url=http://www.lua.org/ftp
extension=tar.gz

prefix=/app/.heroku/vendor
package=$scriptname
dir=$package-$version
archive=$package-$version.$extension
url=$base_url/$archive
archive_dir=$cache_dir/archives
num_cpu=$(grep -c ^bogomips /proc/cpuinfo)

mkdir -p $archive_dir
if [ ! -f $archive_dir/$archive ]
then
  echo "Downloading $url"
  rm -f $archive_dir/$archive.new
  curl -fsLS "$url" > $archive_dir/$archive.new
  mv $archive_dir/$archive.new $archive_dir/$archive
fi

echo "Extracting $archive"
tar -C /tmp -xf $archive_dir/$archive

pushd /tmp/$dir
echo "Building $dir"
make linux MYCFLAGS='-fPIC'
make install INSTALL_TOP=${dest_dir}$prefix

mkdir -p ${dest_dir}$prefix/lib/pkgconfig
cat <<EOT >${dest_dir}$prefix/lib/pkgconfig/lua.pc
prefix=/app/.heroku/vendor
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: Lua
Version: 5.2.3
Description: The Lua interpreter
Libs: -L\${libdir} -llua -lm
Cflags: -I\${includedir}
EOT

# Delete unnecessary man pages
rm -rf ${dest_dir}$prefix/man
popd
