#!/bin/bash

# fail fast
set -o errexit
set -o nounset
set -o pipefail

indent() {
  sed -u 's/^/       /'
}

scriptname=$(basename $0)
case $# in
  4) :;;
  *) echo "$scriptname: usage: $scriptname BUILD_DIR CACHE_DIR DEST_DIR VERSION" >&2; exit 2;;
esac

build_dir="$1"
cache_dir="$2"
dest_dir="$3"
version="$4"

base_url=http://nginx.org/download
extension=tar.gz

prefix=/app/.heroku/vendor
package=$scriptname
dir=$package-$version
archive=$package-$version.$extension
url=$base_url/$archive
archive_dir=$cache_dir/archives
num_cpu=$(grep -c ^bogomips /proc/cpuinfo)

download() {
  url_="$1"
  archive_="$2"
  if [ ! -f $archive_dir/$archive_ ]
  then
    echo "Downloading $url_"
    rm -f $archive_dir/$archive_.new
    curl -fsLS "$url_" > $archive_dir/$archive_.new
    mv $archive_dir/$archive_.new $archive_dir/$archive_
  fi
}

extract() {
  dir_="$1"
  archive_="$2"
  echo "Extracting $dir_"
  tar -C $dir_ -xf $archive_dir/$archive_
}

mkdir -p $archive_dir
download $url $archive
extract /tmp $archive

mod_name=echo-nginx-module
mod_version=0.51
mod_extension=tar.gz
mod_archive=$mod_name-$mod_version.$mod_extension
mod_url=https://github.com/agentzh/$mod_name/archive/v$mod_version.$mod_extension
download $mod_url $mod_archive
extract /tmp $mod_archive

mod_name=nginx-upstream-fair
mod_version=master
mod_extension=tar.gz
mod_archive=$mod_name-$mod_version.$mod_extension
mod_url=https://github.com/gnosek/$mod_name/archive/$mod_version.$mod_extension
download $mod_url $mod_archive
extract /tmp $mod_archive

mod_name=nginx-x-rid-header
mod_version=master
mod_extension=tar.gz
mod_archive=$mod_name-$mod_version.$mod_extension
mod_url=https://github.com/soundcloud/$mod_name/archive/$mod_version.$mod_extension
download $mod_url $mod_archive
extract /tmp $mod_archive

mod_name=ngx_pagespeed
mod_version=1.7.30.3-beta
mod_extension=tar.gz
mod_archive=$mod_name-$mod_version.$mod_extension
mod_url=https://github.com/pagespeed/$mod_name/archive/v$mod_version.$mod_extension
download $mod_url $mod_archive
extract /tmp $mod_archive

dep_name=psol
dep_version=1.7.30.3
dep_extension=tar.gz
dep_archive=$dep_name-$dep_version.$dep_extension
dep_url=https://dl.google.com/dl/page-speed/$dep_name/$dep_version.$dep_extension
download $dep_url $dep_archive
extract /tmp/ngx_pagespeed-1.7.30.3-beta $dep_archive

pushd /tmp/$dir
echo "Building $dir"
./configure \
  --prefix=/state/nginx \
  --sbin-path=$prefix/sbin/nginx \
  --with-cc-opt="$CPPFLAGS" \
  --with-ld-opt="$LDFLAGS" \
  --with-sha1=$prefix/include/openssl \
  --with-md5=$prefix/include/openssl \
  --with-debug \
  --with-http_addition_module \
  --with-http_gzip_static_module \
  --with-http_realip_module \
  --with-http_spdy_module \
  --with-http_ssl_module \
  --with-http_stub_status_module \
  --with-http_sub_module \
  --add-module=/tmp/echo-nginx-module-0.51 \
  --add-module=/tmp/nginx-upstream-fair-master \
  --add-module=/tmp/nginx-x-rid-header-master \
  --add-module=/tmp/ngx_pagespeed-1.7.30.3-beta
make -j$num_cpu
mkdir -p ${dest_dir}$prefix/sbin
install -m0755 objs/nginx ${dest_dir}$prefix/sbin
popd
