#!/bin/bash

# fail fast
set -o errexit
set -o nounset
set -o pipefail

indent() {
  sed -u 's/^/       /'
}

scriptname=$(basename $0)
case $# in
  4) :;;
  *) echo "$scriptname: usage: $scriptname BUILD_DIR CACHE_DIR DEST_DIR VERSION" >&2; exit 2;;
esac

build_dir="$1"
cache_dir="$2"
dest_dir="$3"
version="$4"

version_und=$(echo $version | sed 's/\./_/g')
base_url=https://ftp.mozilla.org/pub/mozilla.org/security/nss/releases/NSS_${version_und}_RTM/src
extension=tar.gz

prefix=/app/.heroku/vendor
package=$scriptname
dir=$package-$version
archive=$package-$version.$extension
url=$base_url/$archive
archive_dir=$cache_dir/archives
num_cpu=$(grep -c ^bogomips /proc/cpuinfo)

mkdir -p $archive_dir
if [ ! -f $archive_dir/$archive ]
then
  echo "Downloading $url"
  rm -f $archive_dir/$archive.new
  curl -fsLS "$url" > $archive_dir/$archive.new
  mv $archive_dir/$archive.new $archive_dir/$archive
fi

echo "Extracting $archive"
tar -C /tmp -xf $archive_dir/$archive

pushd /tmp/$dir/nss
echo "Building $dir"
make -j$num_cpu USE_64=1 BUILD_OPT=1 NSPR_INCLUDE_DIR=$prefix/include/nspr NSPR_LIB_DIR=$prefix/lib

mkdir -p $prefix/bin $prefix/lib $prefix/include/nss
cp ../dist/Linux*.OBJ/bin/* $prefix/bin/
cp ../dist/Linux*.OBJ/lib/* $prefix/lib/
cp -L ../dist/public/nss/* $prefix/include/nss/

# Delete unnecessary man pages
rm -rf $dest_dir/app/.heroku/vendor/share
popd
