#!/bin/bash

# fail fast
set -o errexit
set -o nounset
set -o pipefail

indent() {
  sed -u 's/^/       /'
}

scriptname=$(basename $0)
case $# in
  3) :;;
  *) echo "$scriptname: usage: $scriptname BUILD_DIR CACHE_DIR VERSION" >&2; exit 2;;
esac

build_dir="$1"
cache_dir="$2"
version="$3"

prefix=/app/.heroku/vendor
destdir=/tmp/destdir
package=openssl
dir=$package-$version
archive=$package-$version.tar.gz
url=http://www.openssl.org/source/$archive

echo "-----> Downloading $url"
curl -L# "$url" > /tmp/$archive

echo "-----> Extracting $archive"
tar -C /tmp -xf /tmp/$archive

pushd /tmp/$dir
echo "-----> Building $dir"
./config shared zlib-dynamic --prefix=$prefix --openssldir=/etc/ssl
env CFLAGS=-fPIC LIBS=-ldl make
make INSTALL_PREFIX=$destdir install

# Copy output files into place
mkdir -p $build_dir/.heroku/vendor
rsync -aHSx $destdir/app/.heroku/vendor/. $build_dir/.heroku/vendor/.
popd
