#!/bin/bash

# fail fast
set -o errexit
set -o nounset
set -o pipefail

indent() {
  sed -u 's/^/       /'
}

scriptname=$(basename $0)
case $# in
  4) :;;
  *) echo "$scriptname: usage: $scriptname BUILD_DIR CACHE_DIR DEST_DIR VERSION" >&2; exit 2;;
esac

build_dir="$1"
cache_dir="$2"
dest_dir="$3"
version="$4"

base_url=http://www.openssl.org/source
extension=tar.gz

prefix=/app/.heroku/vendor
package=$scriptname
dir=$package-$version
archive=$package-$version.$extension
url=$base_url/$archive
archive_dir=$cache_dir/archives
num_cpu=$(grep -c ^bogomips /proc/cpuinfo)

mkdir -p $archive_dir
if [ ! -f $archive_dir/$archive ]
then
  echo "Downloading $url"
  rm -f $archive_dir/$archive.new
  curl -fL# "$url" > $archive_dir/$archive.new
  mv $archive_dir/$archive.new $archive_dir/$archive
fi

echo "Extracting $archive"
tar -C /tmp -xf $archive_dir/$archive

pushd /tmp/$dir
echo "Building $dir"
./config shared zlib-dynamic --prefix=$prefix --openssldir=/etc/ssl
# XXX: Don't use -j$num_cpu because it fails for some reason
env CFLAGS=-fPIC LIBS=-ldl make
make INSTALL_PREFIX=$dest_dir install_sw
popd
